name: SXItemExpansion
description: $description
version: '${version}'

main: me.qq3393525847.sxitemexpansion.SXItemExpansion
api-version: '1.21'
load: POSTWORLD

authors: [ qq3393525847 ]

dependencies:
  - SX-Item
